[package]
name = "stress_test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stress_test"
path = "src/main.rs"

[dependencies]
platforms = { path = "../platforms" }
backend = { path = "../backend" }
tokio = { version = "1.45.1", features = ["full"] }