[package]
name = "platforms"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = "2.0.12"
tokio = { workspace = true }
bit-vec = "0.8"
tao = "0.33.0"
softbuffer = "0.4.6"
anyhow = "1.0.98"
log = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = [
    "Win32_Foundation",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Graphics_Capture",
    "Graphics_DirectX_Direct3D11",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Dwm",
    "Win32_System_WinRT_Graphics_Capture",
    "Win32_System_WinRT_Direct3D11",
    "Win32_System_Threading",
    "System",
] }

[target.'cfg(windows)'.build-dependencies]
tauri-winres = "0.3.1"

[target.'cfg(target_os = "macos")'.dependencies]
screenshots = "0.8"
core-graphics = "0.23"
core-foundation = "0.9"
